# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.operation.slideshare.slideshow:
        class: CampaignChain\Operation\SlideShareBundle\EntityService\Slideshow
        arguments: [ @doctrine.orm.entity_manager ]
    campaignchain.job.operation.slideshare.publish_slideshow:
        class: CampaignChain\Operation\SlideShareBundle\Job\PublishSlideshow
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.job.report.slideshare.publish_slideshow:
        class: CampaignChain\Operation\SlideShareBundle\Job\ReportPublishSlideshow
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
        