# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#    campaign_chain_operation_slide_share.example:
#        class: CampaignChain\Operation\SlideShareBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    campaignchain.operation.slideshare.slideshow:
        class: CampaignChain\Operation\SlideShareBundle\EntityService\Slideshow
        arguments: [ @doctrine.orm.entity_manager ]
    campaignchain.job.operation.slideshare.publish_slideshow:
        class: CampaignChain\Operation\SlideShareBundle\Job\PublishSlideshow
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
        